[book]
title = "Digital Passport Model Assessment Workbench Documentation"
authors = ["CE-RISE consortium"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://codeberg.org/CE-RISE-software/dp-assessment-workbench"
sidebar-header-nav = true
additional-js = ["theme/custom.js"]
